export const APP_EDUCATION_TIPS = [
  // 🛡️ SULAMA DAĞITIM ÖNCESİ HAZIRLIK (MOBİLİZASYON)
  { text: "Sulama sezonu başlamadan önce, tüm dağıtım kanallarının fiziksel durumu kontrol edilmeli ve temizlik çalışmaları 'Altyapı Takip' sistemine işlenmelidir.", author: "Eğitim: Sezon Hazırlığı" },
  { text: "Dağıtım öncesi saha keşfinde saptanan teknik aksaklıklar, 'Teknik Arıza' formu ile ivedilikle ilgili birime raporlanmalıdır.", author: "Eğitim: Saha Keşfi" },
  { text: "Mevki bazlı su dağıtım planları oluşturulurken, bir önceki yılın tüketim verileri 'Stratejik Tahmin' ekranından analiz edilmelidir.", author: "Eğitim: Planlama Esasları" },
  { text: "Meravların zimmetli ekipmanları ve mühürlü koçan serileri, dağıtım öncesinde idari amir tarafından sarsılmaz bir nizamla kontrol edilmelidir.", author: "Eğitim: Zimmet Yönetimi" },
  { text: "Dağıtım rotaları belirlenirken, coğrafi yakınlık ve suyun akış hiyerarşisi operasyonel verimlilik için esas alınmalıdır.", author: "Eğitim: Rota Optimizasyonu" },
  { text: "Sezon açılışından önce tüm mükelleflerin 'Cari Bakiye' durumları kontrol edilmeli, borcu olanlar bildirim sistemine sevk edilmelidir.", author: "Eğitim: Ön Denetim" },
  { text: "Dağıtım kanallarındaki kapakların (vunaların) bakım tarihleri, sistemdeki envanter kayıtları üzerinden güncellenmelidir.", author: "Eğitim: Bakım Onarım" },
  { text: "Sulama takvimleri, mahalle muhtarlıklarına ve ilgili paydaşlara resmi yazışma kanalları ile ivedilikle tebliğ edilmelidir.", author: "Eğitim: Bilgilendirme" },

  // 🛡️ DAĞITIM ESNASI VE SAHA YÖNETİMİ (OPERASYON)
  { text: "Saha operasyonları sırasında su saatlerinden alınan değerler, 'Seri Veri Girişi' modülü ile anlık olarak merkeze iletilmelidir.", author: "Eğitim: Anlık Veri Akışı" },
  { text: "Taşınmaz başında yapılan tespitlerde, zilyet değişikliği saptanırsa bu durum 'Saha Notu' olarak ivedilikle kaydedilmelidir.", author: "Eğitim: Zilyetlik Takibi" },
  { text: "Su dağıtımı sırasında oluşabilecek kaçak veya yetkisiz kullanımlar, 'İdari Yaptırım' protokolü çerçevesinde mühürlenmelidir.", author: "Eğitim: Denetim Standartları" },
  { text: "Mevsimsel hava koşulları nedeniyle dağıtım takviminde yapılan değişiklikler, mükelleflere toplu SMS yoluyla bildirilmelidir.", author: "Eğitim: Kriz Yönetimi" },
  { text: "Meravlar, her birim su dağıtımı için sistemden 'Tahakkuk Onayı' almadan fiş kesmemelidir.", author: "Eğitim: İş Akış Disiplini" },
  { text: "Dağıtım esnasında suyun debisindeki anomaliler, altyapıdaki gizli arızaların saptanması için istatistiki olarak izlenmelidir.", author: "Eğitim: Teknik Analiz" },
  { text: "Meravlar arasındaki koordinasyon, sistemdeki 'Merav Lokasyon' ve 'Görev Durumu' ekranları üzerinden sağlanır.", author: "Eğitim: Operasyonel Sevk" },
  { text: "Mükellef talepleri (su saati değişikliği vb.), Merav ekibi tarafından 'İş Emri'ne dönüştürülmeli; geçmiş fişlerin sarsılmaz bütünlüğü korunmalıdır.", author: "Eğitim: Talep Yönetimi" },

  // 🛡️ DAĞITIM SONRASI VE MUTABAKAT (DEMOBİLİZASYON)
  { text: "Günlük dağıtım işlemleri sona erdiğinde, 'Kasa Kapanışı' ile fiili tahsilat ve sistem kayıtları sarsılmaz bir nizamla mutabık kılınmalıdır.", author: "Eğitim: Gün Sonu Mutabakatı" },
  { text: "Haftalık periyotlarda, gerçekleştirilen su dağıtımı ile hedeflenen dağıtım oranları 'Performans Analizi' ekranından kıyaslanmalıdır.", author: "Eğitim: Verimlilik Ölçümü" },
  { text: "Sezon sonunda tüm sulama fişleri arşive sevk edilmeli, ödenmemiş borçlar 'İcra ve Takip' sürecine ivedilikle devredilmelidir.", author: "Eğitim: Alacak Yönetimi" },
  { text: "Dağıtım sonrası kanallarda kalan suyun tahliyesi ve vanaların kışlık bakımı, sistemde 'Sezon Sonu Bakım' olarak işaretlenmelidir.", author: "Eğitim: Tesis Koruma" },
  { text: "Mükellef itirazları, dağıtım kayıtları ve merav notları eşliğinde 'İdari Komisyon' tarafından karara bağlanmalıdır.", author: "Eğitim: İhtilaf Çözümü" },
  { text: "Dağıtım sonrası düzenlenen 'Mali Durum Raporu', kurum icra kurulune sunulmak üzere resmi formatta çıktı alınmalıdır.", author: "Eğitim: Kurumsal Raporlama" },
  { text: "Saha teçhizatlarının (saatler, tabletler) sezon sonu bakımı ve depolanması, 'Envanter Hareketleri'ne işlenmelidir.", author: "Eğitim: Lojistik Kapanış" },

  // 🛡️ SU TARİFESİ VE MALİ YÜKÜMLÜLÜKLER
  { text: "Su birim fiyatları, her yıl Kurum Yönetim Kurulu kararı ile belirlenen 'Resmi Tarife' üzerinden sisteme tanımlanmalıdır.", author: "Eğitim: Tarife Mevzuatı" },
  { text: "Kademeli su tarifesi, kullanım miktarı arttıkça birim maliyeti otomatik olarak güncelleyerek tasarrufu teşvik eder.", author: "Eğitim: Tasarruf Odaklılık" },
  { text: "Gecikme zammı, 6183 sayılı kanun ve ilgili mevzuat çerçevesinde sistem tarafından günlük olarak sarsılmaz bir hızla hesaplanır.", author: "Eğitim: Hukuki Faiz" },
  { text: "Tarımsal sulama ile içme suyu tarifeleri arasındaki farklar, taşınmaz tipine göre sistemde otomatik olarak ayrıştırılmaktadır.", author: "Eğitim: Vergilendirme Rejimi" },
  { text: "Mali muafiyet veya indirim tanımları, sadece resmi meclis kararı ve ilgili evrakın sisteme yüklenmesi ile aktif edilebilir.", author: "Eğitim: İstisna Yönetimi" },
  { text: "Tahsilat makbuzlarındaki QR kod, mükellefin ödeme geçmişini ve güncel borç durumunu dijital olarak doğrular.", author: "Eğitim: Dijital Şeffaflık" },
  { text: "Peşin ödemelerde uygulanan kurumsal indirimler, tahakkuk aşamasında sistem tarafından otomatik olarak düşülür.", author: "Eğitim: Ödeme Teşvikleri" },
  { text: "İdari para cezaları, mevzuata aykırı su kullanımı tespit edilen mükellefin siciline sarsılmaz bir nizamla işlenmelidir.", author: "Eğitim: Caydırıcı Denetim" },

  // 🛡️ SİSTEM VE VERİ YÖNETİMİ STANDARTLARI
  { text: "Vatandaş Kimlik Doğrulama özelliği, uygulama kullanıcısının Türkiye Cumhuriyeti kimlik numarası ile resmi olarak ilişkilendirilmesini sağlar.", author: "Eğitim: Kimlik Yönetimi" },
  { text: "Veri tabanı logları, adli bilişim standartlarında kayıt tutarak her işlemin izlenebilirliğini sarsılmaz bir nizamla sağlar.", author: "Eğitim: Şeffaflık ve Hesap Verilebilirlik" },
  { text: "Yedekleme dosyaları (Backup), her mesai bitiminde otomatik olarak harici güvenli depolama birimlerine aktarılmaktadır.", author: "Eğitim: Veri Güvenliği" },
  { text: "Uygulama erişim şifreleri, periyodik olarak güncellenmeli ve siber güvenlik protokolleri gereği kimseyle paylaşılmamalıdır.", author: "Eğitim: Bilgi Güvenliği" },
  { text: "Analitik Komuta Merkezi, kurum yönetim kurulu toplantılarında sunulabilecek resmi veri setlerini sarsılmaz bir hızla üretir.", author: "Eğitim: Stratejik Planlama" },
  { text: "Eksik evraklı taşınmaz kayıtları, 'Arşiv Denetimi' raporunda listelenerek eksikliklerin giderilmesi için takip edilir.", author: "Eğitim: Dokümantasyon" },
  { text: "Klavye kısayolları (Ctrl+S gibi), kayıt işlemlerinde operasyonel hızı sarsılmaz bir nizamla artırır.", author: "Eğitim: Operasyonel Hız" },
  { text: "Veri tabanı indeksleme süreçleri, milyonlarca kayıt arasında milisaniyeler bazında sorgulama yapılmasına imkan verir.", author: "Eğitim: Teknik Altyapı" },
  { text: "Mükellef kartına eklenen özel notlar, geçmişe dönük idari ihtilafların çözümünde resmi referans niteliği taşır.", author: "Eğitim: Kayıt Arşivi" },
  { text: "Makbuz yazdırma ayarlarından, yazıcı tipi ve kağıt boyutu kurumsal standartlara göre özelleştirilebilir.", author: "Eğitim: Donanım Yapılandırma" },
  { text: "Otomatik faiz hesaplama modülü, geciken ödemeleri resmi mevzuat oranlarına göre sarsılmaz bir hızla günceller.", author: "Eğitim: Finansal Disiplin" },
  { text: "Arşivleme özelliği, 10 yıldan eski kayıtları aktif listeden çıkararak sistem performansını sarsılmaz bir nizamla korur.", author: "Eğitim: Veri Yaşam Döngüsü" },
  { text: "Hata bildirimleri, sistem mühendislerine teknik telemetri verileri ile birlikte otomatik olarak iletilmektedir.", author: "Eğitim: Hata Yönetimi" },
  { text: "Vatandaş TC Kimlik algoritması, sahte veya hatalı numara girişlerini sarsılmaz bir nizamla engeller.", author: "Eğitim: Veri Doğrulama" },
  { text: "Kasa açılış bakiyesi, bir önceki günün kapanış bakiyesi ile kurumsal bir bütünlük içerisinde olmalıdır.", author: "Eğitim: Mali Mutabakat" },
  { text: "Personel kartlarındaki görev tanımları, sistem yetkilendirme (ACL) mimarisi ile entegre çalışmaktadır.", author: "Eğitim: Yetki Yönetimi" },
  { text: "Dönem kapatma işlemi geri alınamaz; sezon kapatılmadan önce tüm veri girişlerinin tamamlandığından emin olunmalıdır.", author: "Eğitim: Sezon Yönetimi" },
  { text: "Kasa hareketleri dökümünde 'İptal' edilen işlemler kırmızı ile işaretlenmekte olup, bakiye hesaplamalarına dahil edilmemektedir.", author: "Eğitim: Muhasebe İzleme" },
  { text: "Coğrafi Bilgi Sistemi (CBS) üzerinden taşınmazların konumları izlenebilir, sınır ihlalleri mekansal olarak tespit edilebilir.", author: "Eğitim: Coğrafi Analiz" },
  { text: "Vatandaş kartındaki iletişim bilgilerinin güncelliği, bilgilendirme mesajlarının resmi kanallar üzerinden ulaştırılması için kritiktir.", author: "Eğitim: İletişim Protokolü" },
  { text: "Veri aktarım süreçlerinde (Excel), kolon başlıklarının kurumsal şablona tam uyumlu olması gerekmektedir.", author: "Eğitim: Veri Entegrasyonu" },
  { text: "Sınır ihlali ve limit aşımı raporları, su kullanım hakkını belirlenen orandan fazla kullanan mükellefleri listelemektedir.", author: "Eğitim: Denetim ve Kontrol" },
  { text: "Tahsilat makbuzlarındaki 'Tahsildar' alanı, işlemi gerçekleştiren yetkili personelin hukuki sorumluluğunu kayıt altına alır.", author: "Eğitim: İdari Sorumluluk" },
  { text: "Yeni yerleşim birimi eklenirken, bağlı bulunduğu idari bölge ve sorumlu merav seçilmesi zorunludur.", author: "Eğitim: İdari Yapı" },
  { text: "Gece Modu özelliği, düşük ışıklı çalışma ortamlarında göz sağlığını korumak amacıyla geliştirilmiştir; Ayarlar sekmesinden erişilebilir.", author: "Eğitim: Kullanıcı Deneyimi" },
  { text: "Resmi belge çıktıları kurumsal baskı düzeninde oluşturulmakta olup, A4 formatına tam uyum sağlamaktadır.", author: "Eğitim: Raporlama ve Çıktı" },
  { text: "Merava zimmetli koçan serileri düzenli takip edilmeli, kullanım süresi dolan belgeler arşive teslim edilmelidir.", author: "Eğitim: Saha Disiplini" },
  { text: "Sistem üzerindeki 'Yenile' butonu, merkezi veritabanı ile terminal arasındaki veri senkronizasyonunu sağlamaktadır.", author: "Eğitim: Veri Eşitleme" },
  { text: "Bölgesel sulama raporları, mevkilerin su tüketim oranlarını idari ve istatistiki yöntemlerle analiz etmenize olanak tanır.", author: "Eğitim: Analiz ve İstatistik" },
  { text: "Kasa bakiye uyumsuzluğu durumunda 'Düzeltme Fişi' oluşturulmalı ve işlemin gerekçesi resmi olarak kaydedilmelidir.", author: "Eğitim: Muhasebe Standartları" },
  { text: "Ödenmemiş borç kaydı bulunan mükelleflere yeni bir kullanım hakkı tanımlanırken sistem otomatik uyarı vermektedir.", author: "Eğitim: Alacak Takibi" },
  { text: "Uygulama ara yüzündeki renk kodları (Yeşil: Ödendi, Kırmızı: Gecikti), görsel denetimi kolaylaştırır.", author: "Eğitim: Görsel Yönetim" },
  { text: "İdari sınır değişiklikleri, sistemdeki mahalle ve mevki hiyerarşisine ivedilikle yansıtılmalıdır.", author: "Eğitim: İdari Değişim" },
  { text: "Sistem, her ayın sonunda otomatik olarak 'Mali Durum Özeti' raporu üreterek yönetime sunar.", author: "Eğitim: Yönetim Raporlaması" },
  { text: "Toplu SMS modülü, borç hatırlatmalarını sarsılmaz bir hızla mükellef telefonlarına ulaştırır.", author: "Eğitim: Bildirim Sistemleri" },
  { text: "Kasa dökümü alınmadan önce tüm aktif sekmelerin kapatılması, veri tutarlılığı açısından önerilir.", author: "Eğitim: Sistem Kullanım Adabı" },
  { text: "Mükellef vefat durumunda, yasal varislerin kayıtları sarsılmaz bir nizamla sisteme işlenmelidir.", author: "Eğitim: Veraset İşlemleri" },
  { text: "Sulama kanallarının bakım periyotları, sistemdeki 'Altyapı Takip' sekmesinden izlenebilir.", author: "Eğitim: Altyapı Yönetimi" },
  { text: "Veri şifreleme standartları (AES-256), vatandaş bilgilerini siber tehditlere karşı sarsılmaz bir nizamla korur.", author: "Eğitim: Siber Güvenlik" },
  { text: "Otomatik güncelleme kontrolü, sistemin her zaman en son güvenlik yamalarına sahip olmasını sağlar.", author: "Eğitim: Yazılım Bakımı" },
  { text: "Mali raporlardaki 'Sapma Analizi', beklenen ve gerçekleşen gelir arasındaki farkları listeler.", author: "Eğitim: Finansal Analiz" },
  { text: "Uygulama yardım dökümanları, her ekranın sağ üst köşesindeki soru işareti ikonu ile sarsılmaz bir nizamla açılır.", author: "Eğitim: Kullanıcı Desteği" },
  { text: "Veri girişi sırasında yapılan hatalar, 'İşlem Geri Al' butonu ile 5 dakika içerisinde düzeltilebilir.", author: "Eğitim: Hata Düzeltme" },
  { text: "Toplu tahakkuk özelliği, tüm bir mahalleye aynı anda sezonluk borç tanımlanmasını sağlar.", author: "Eğitim: Toplu İşlemler" },
  { text: "İmza sirküleri değişen personelin yetkileri, sistem üzerinden ivedilikle güncellenmelidir.", author: "Eğitim: Kurumsal Kimlik" },
  { text: "Vatandaşların önceki adres bilgileri, 'İletişim Tarihçesi' sekmesinde muhafaza edilmektedir.", author: "Eğitim: Veri Arşivi" },
  { text: "Sistem performansı için haftada bir kez 'Önbellek Temizliği' yapılması tavsiye edilir.", author: "Eğitim: Sistem Optimizasyonu" },
  { text: "Mali fişlerdeki QR kod, belgenin dijital aslına sarsılmaz bir hızla erişim imkanı tanır.", author: "Eğitim: Dijital Doğrulama" },
  { text: "Ödeme noktaları (Vezne, Online, Banka) arasındaki veri entegrasyonu sarsılmaz bir nizamla çalışır.", author: "Eğitim: Entegrasyon Yönetimi" },
  { text: "Yıllık bütçe planlamasında, geçmiş yılların su tüketim verileri ana referans olarak alınır.", author: "Eğitim: Stratejik Tahmin" },
  { text: "Personel performans metrikleri, işlem hızı ve hata payı üzerinden sistemce puanlanmaktadır.", author: "Eğitim: Verimlilik Ölçümü" },
  { text: "Mahalle muhtarları için özel 'Bilgi İzleme' ekranı, bölgelerindeki sulama durumunu görmelerini sağlar.", author: "Eğitim: Paydaş İletişimi" },
  { text: "Yeni mevzuat değişiklikleri, sistem bildirimleri aracılığıyla kullanıcılara sarsılmaz bir hızla tebliğ edilir.", author: "Eğitim: Mevzuat Takibi" },
  { text: "Veri tabanı logları, adli bilişim standartlarında kayıt tutarak hukuki koruma sağlar.", author: "Eğitim: Adli Bilişim" },
  { text: "Uygulama açılış hızı, donanım ivmelendirme (GPU) desteği ile sarsılmaz bir nizamla optimize edilmiştir.", author: "Eğitim: Teknik Performans" },
  { text: "Kasa personeli değişiminde 'Nöbet Devri' formu sistem üzerinden dijital olarak imzalanmalıdır.", author: "Eğitim: Nöbet Yönetimi" },
  { text: "Fiziksel arşiv kutu numaraları, sistemdeki dijital kayıtlarla hiyerarşik uyum içerisinde olmalıdır.", author: "Eğitim: Fiziksel Arşiv" },
  { text: "Su saatleri montaj tarihleri, garanti takibi için taşınmaz detaylarına sarsılmaz bir nizamla işlenmelidir.", author: "Eğitim: Envanter Takibi" },
  { text: "Gecikme zammı muafiyetleri, sadece meclis kararı ve resmi yazı ile sisteme tanımlanabilir.", author: "Eğitim: İstisna Yönetimi" },
  { text: "Sistem anahtarı (License Key), kurum adına tescilli olup izinsiz kopyalanamaz.", author: "Eğitim: Fikri Mülkiyet" },
  { text: "Mükellef şikayet yönetimi modülü, çözüm sürecini sarsılmaz bir hızla takip ve rapor eder.", author: "Eğitim: Hizmet Kalitesi" },
  { text: "Veri giriş terminalleri, siber güvenlik politikaları gereği mesai bitiminde güvenli çıkış yapmalıdır.", author: "Eğitim: Operasyonel Güvenlik" },
  { text: "Dijital mühür teknolojisi, raporların değiştirilmediğini sarsılmaz bir nizamla garanti altına alır.", author: "Eğitim: Veri Bütünlüğü" },
  { text: "Saha operasyonlarında tablet kullanımı, verinin kaynağında sarsılmaz bir hızla toplanmasını sağlar.", author: "Eğitim: Saha Otomasyonu" },
  { text: "Hizmet içi eğitim videoları, 'Eğitim Paneli' sekmesinden sarsılmaz bir nizamla izlenebilir.", author: "Eğitim: Sürekli Gelişim" },
  { text: "Veri senkronizasyon hataları durumunda, 'Zorunlu Eşitleme' protokolü ivedilikle başlatılmalıdır.", author: "Eğitim: Kriz Yönetimi" },
  { text: "Mükellef memnuniyet anketleri, sistem üzerinden periyodik olarak analiz edilmektedir.", author: "Eğitim: Kurumsal Gelişim" },
  { text: "Yazılımsal destek talepleri, 'Destek Masası' üzerinden bilet (ticket) sistemiyle takip edilir.", author: "Eğitim: Teknik Destek" },
  { text: "Mali yıl açılışında, bir önceki yıldan devreden tüm bakiyeler sarsılmaz bir nizamla kontrol edilmelidir.", author: "Eğitim: Yıl Sonu Kapanışı" },
  { text: "Sistem, yetkisiz erişim denemelerini sarsılmaz bir hızla saptayarak güvenlik birimine raporlar.", author: "Eğitim: Güvenlik Denetimi" },
  { text: "Veri standardizasyonu, kurumlar arası veri paylaşımında (E-Devlet vb.) tam uyumluluk sağlar.", author: "Eğitim: Birlikte Çalışabilirlik" },
  { text: "Sarsılmaz bir nizam ve idari vakarla, Kurum Başkanlığı hizmet kalitesini sarsılmaz bir hızla artırmaktayız.", author: "Eğitim: Kurumsal Vizyon" },
  { text: "Sonuç odaklı idari yönetim, verinin doğru işlenmesi ve analizi ile sarsılmaz bir nizamla mümkündür.", author: "Eğitim: Yönetim İlkeleri" }
];
