export const DataMapper = {
  toCitizen: (db: any) => ({
    id: db.id,
    firstName: db.Ad,
    lastName: db.Soyad,
    tckn: db.TCKN,
    fatherName: db.Baba_Adi,
    motherName: db.Ana_Adi,
    birthPlace: db.Dogum_Yeri,
    birthDate: db.Dogum_Tarihi,
    gender: db.Cinsiyet,
    phone: db.Telefon,
    mobile: db.Cep_Telefonu,
    address: db.Adres,
    registrationNumber: db.Sicil_No,
  }),
  toDbCitizen: (app: any) => ({
    id: app.id,
    Ad: app.firstName,
    Soyad: app.lastName,
    TCKN: app.tckn,
    Baba_Adi: app.fatherName,
    Ana_Adi: app.motherName,
    Dogum_Yeri: app.birthPlace,
    Dogum_Tarihi: app.birthDate,
    Cinsiyet: app.gender,
    Telefon: app.phone,
    Cep_Telefonu: app.mobile,
    Adres: app.address,
    Sicil_No: app.registrationNumber,
  }),
  toLandRecord: (db: any) => ({
    id: db.id,
    location: db.Mevki,
    island: db.Ada,
    parcel: db.Parsel,
    area_m2: db.Alan_m2,
    type: db.Nitelik,
    propertyNo: db.Tasinmaz_No,
    ownerType: db.Sahip_Turu,
    ownerTCKN: db.Tapu_Sahibi_TCKN,
    shareRatio: db.Hisse_Orani,
    registrationDate: db.Tescil_Tarihi,
    journalNo: db.Yevmiye_No,
    waterRightHourly: db.Su_Hakki_Saatlik,
    underCanalLevel: db.Kanal_Seviyesi_Altinda === 1 || db.Kanal_Seviyesi_Altinda === "Evet",
    irrigatedByCanal: db.Kanal_Suyu_Ile_Sulanan === 1 || db.Kanal_Suyu_Ile_Sulanan === "Evet",
    shareholdersJson: db.Hissedarlar_JSON,
    relatedPersonsJson: db.Ilgili_Kisiler_JSON,
    notes: db.Dusunceler,
  }),
  toDbLandRecord: (app: any) => ({
    id: app.id,
    Mevki: app.location,
    Ada: app.island,
    Parsel: app.parcel,
    Alan_m2: app.area_m2,
    Nitelik: app.type,
    Tasinmaz_No: app.propertyNo,
    Sahip_Turu: app.ownerType,
    Tapu_Sahibi_TCKN: app.ownerTCKN,
    Hisse_Orani: app.shareRatio,
    Tescil_Tarihi: app.registrationDate,
    Yevmiye_No: app.journalNo,
    Su_Hakki_Saatlik: app.waterRightHourly,
    Kanal_Seviyesi_Altinda: app.underCanalLevel ? "Evet" : "Hayır",
    Kanal_Suyu_Ile_Sulanan: app.irrigatedByCanal ? "Evet" : "Hayır",
    Hissedarlar_JSON: app.shareholdersJson,
    Ilgili_Kisiler_JSON: app.relatedPersonsJson,
    Dusunceler: app.notes,
  })
};

